### ISSUE TITLE
ログイン履歴をredisなどに載せ替える

### ISSUE THREAD

**Issue by mism-mism** [MasamiMishima/waiwai_isucon_4#11]
ログイン履歴をredisなどに載せ替える

_Originally posted by @IkezoeMakoto in https://github.com/MasamiMishima/waiwai_isucon_4/issues/4#issuecomment-480555491_

**Comment by okashoi** [comment]
redis をインストールするぞい

**Comment by okashoi** [comment]
`sudo yum --enablerepo=epel install -y redis`
