### ISSUE TITLE
不要ディレクトリ消す

### ISSUE THREAD

**Issue by mism-mism** [MasamiMishima/waiwai_isucon_4#12]
不要ディレクトリ消す

_Originally posted by @MasamiMishima in https://github.com/MasamiMishima/waiwai_isucon_4/issues/4#issuecomment-480556292_

**Comment by IkezoeMakoto** [comment]
https://github.com/MasamiMishima/waiwai_isucon_4/compare/5157216a8886...0c7d4a7912e7
